DROP TABLE IF EXISTS query_audit;
DROP TABLE IF EXISTS sales_order_item;
DROP TABLE IF EXISTS sales_order;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS app_user;
DROP TABLE IF EXISTS department;

CREATE TABLE department (
    id BIGINT PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE app_user (
    id BIGINT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(80) NOT NULL,
    data_scope VARCHAR(20) NOT NULL,
    department_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_user_department FOREIGN KEY (department_id) REFERENCES department(id),
    CONSTRAINT ck_user_scope CHECK (data_scope IN ('ALL', 'DEPARTMENT'))
);

CREATE TABLE customer (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    segment VARCHAR(30) NOT NULL,
    city VARCHAR(60) NOT NULL
);

CREATE TABLE product (
    id BIGINT PRIMARY KEY,
    sku VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    category VARCHAR(60) NOT NULL,
    unit_price DECIMAL(12, 2) NOT NULL
);

CREATE TABLE sales_order (
    id BIGINT PRIMARY KEY,
    order_no VARCHAR(40) NOT NULL UNIQUE,
    order_date DATE NOT NULL,
    customer_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    total_amount DECIMAL(14, 2) NOT NULL,
    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customer(id),
    CONSTRAINT fk_order_department FOREIGN KEY (department_id) REFERENCES department(id)
);

CREATE TABLE sales_order_item (
    id BIGINT PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(12, 2) NOT NULL,
    line_amount DECIMAL(14, 2) NOT NULL,
    CONSTRAINT fk_item_order FOREIGN KEY (order_id) REFERENCES sales_order(id),
    CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE query_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id VARCHAR(50) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    conversation_id VARCHAR(120) NOT NULL,
    sql_text CLOB NOT NULL,
    success BOOLEAN NOT NULL,
    duration_ms BIGINT NOT NULL,
    error_message VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE INDEX idx_order_date ON sales_order(order_date);
CREATE INDEX idx_order_department ON sales_order(department_id);
CREATE INDEX idx_item_order ON sales_order_item(order_id);
